class Urls:
    HOME_URL = "https://eu.store.square-enix-games.com"
    LAST_CHANCE_URL = HOME_URL + "/last-chance"
    JUST_IN_URL = HOME_URL + "/just-in"
    FRANCHISE_URL = HOME_URL + "/franchise"
    VIDEO_GAMES_URL = HOME_URL + "/video-games"
    MERCHANDISE_URL = HOME_URL + "/merchandise"
    FFXIV_MERCHANDISE = HOME_URL + "/ffxiv-merchandise"
    REWARDS_URL = HOME_URL + "/rewards"
    OFFERS_URL = HOME_URL + "/offers"